/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.Investidor;
import controller.Controller_Investidor;
/**
 *
 * @author rgara
 */
public class investidor_window extends javax.swing.JFrame {

    Controller_Investidor control;
    /**
     * Creates new form investidor_window
     */
    public investidor_window(Investidor investidor) {
        initComponents();
        control = new Controller_Investidor(this, investidor);
        System.out.println(investidor);
    }

    public JTextArea getConsultaCotacao() {
        return ConsultaCotacao;
    }

    public void setConsultaCotacao(JTextArea ConsultaCotacao) {
        this.ConsultaCotacao = ConsultaCotacao;
    }

    public JButton getBtnComprarCrypto() {
        return btnComprarCrypto;
    }

    public void setBtnComprarCrypto(JButton btnComprarCrypto) {
        this.btnComprarCrypto = btnComprarCrypto;
    }

    public JButton getBtnConsultarExtrato() {
        return btnConsultarExtrato;
    }

    public void setBtnConsultarExtrato(JButton btnConsultarExtrato) {
        this.btnConsultarExtrato = btnConsultarExtrato;
    }

    public JButton getBtnConsultarSaldo() {
        return btnConsultarSaldo;
    }

    public void setBtnConsultarSaldo(JButton btnConsultarSaldo) {
        this.btnConsultarSaldo = btnConsultarSaldo;
    }

    public JButton getBtnDepositar() {
        return btnDepositar;
    }

    public void setBtnDepositar(JButton btnDepositar) {
        this.btnDepositar = btnDepositar;
    }

    public JButton getBtnSacar() {
        return btnSacar;
    }

    public void setBtnSacar(JButton btnSacar) {
        this.btnSacar = btnSacar;
    }

    public JButton getBtnVenderCrypto() {
        return btnVenderCrypto;
    }

    public void setBtnVenderCrypto(JButton btnVenderCrypto) {
        this.btnVenderCrypto = btnVenderCrypto;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblInstrucao() {
        return lblInstrucao;
    }

    public void setLblInstrucao(JLabel lblInstrucao) {
        this.lblInstrucao = lblInstrucao;
    }

    public Controller_Investidor getControl() {
        return control;
    }

    public void setControl(Controller_Investidor control) {
        this.control = control;
    }

    public JButton getBtnAlterarSenha() {
        return btnAlterarSenha;
    }

    public void setBtnAlterarSenha(JButton btnAlterarSenha) {
        this.btnAlterarSenha = btnAlterarSenha;
    }

    public JButton getBtnatualizarCotacao() {
        return btnatualizarCotacao;
    }

    public void setBtnatualizarCotacao(JButton btnatualizarCotacao) {
        this.btnatualizarCotacao = btnatualizarCotacao;
    }

    public JButton getBtnsair() {
        return btnsair;
    }

    public void setBtnsair(JButton btnsair) {
        this.btnsair = btnsair;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstrucao = new javax.swing.JLabel();
        btnConsultarSaldo = new javax.swing.JButton();
        btnConsultarExtrato = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnSacar = new javax.swing.JButton();
        btnComprarCrypto = new javax.swing.JButton();
        btnVenderCrypto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsultaCotacao = new javax.swing.JTextArea();
        btnatualizarCotacao = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        btnAlterarSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela investidor");

        lblInstrucao.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblInstrucao.setText("Selecione uma das opções");

        btnConsultarSaldo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConsultarSaldo.setText("Consultar saldo");

        btnConsultarExtrato.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConsultarExtrato.setText("Consultor extrato");

        btnDepositar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDepositar.setText("Depositar");

        btnSacar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        btnComprarCrypto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnComprarCrypto.setText("Comprar Crypto");

        btnVenderCrypto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVenderCrypto.setText("Vender Crypto");

        ConsultaCotacao.setColumns(20);
        ConsultaCotacao.setRows(5);
        jScrollPane1.setViewportView(ConsultaCotacao);

        btnatualizarCotacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnatualizarCotacao.setText("Atualizar cotação");

        btnsair.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnsair.setText("Sair");
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        btnAlterarSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAlterarSenha.setText("Alterar senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblInstrucao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnComprarCrypto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVenderCrypto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultarExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnatualizarCotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlterarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblInstrucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConsultarExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnatualizarCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComprarCrypto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVenderCrypto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsairActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(investidor_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(investidor_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(investidor_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(investidor_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new investidor_window().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ConsultaCotacao;
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnComprarCrypto;
    private javax.swing.JButton btnConsultarExtrato;
    private javax.swing.JButton btnConsultarSaldo;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnVenderCrypto;
    private javax.swing.JButton btnatualizarCotacao;
    private javax.swing.JButton btnsair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInstrucao;
    // End of variables declaration//GEN-END:variables
}
