/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Investidor;
import controller.Controller_AlterarSenha;

/**
 *
 * @author rgara
 */
public class Alterar_window extends javax.swing.JFrame {

    private Controller_AlterarSenha control;
    private Investidor investidor;
    /**
     * Creates new form Alterar_window
     */
    public Alterar_window(Investidor investidor) {
        initComponents();
        this.control = new Controller_AlterarSenha(this, investidor);
        this.investidor = investidor;
    }

    public JTextField getInsertAlterar_cpf() {
        return InsertAlterar_cpf;
    }

    public void setInsertAlterar_cpf(JTextField InsertAlterar_cpf) {
        this.InsertAlterar_cpf = InsertAlterar_cpf;
    }

    public JTextField getInsertAlterar_senhaNova() {
        return InsertAlterar_senhaNova;
    }

    public void setInsertAlterar_senhaNova(JTextField InsertAlterar_senhaNova) {
        this.InsertAlterar_senhaNova = InsertAlterar_senhaNova;
    }

    public JPanel getPainel_alterar_senha() {
        return Painel_alterar_senha;
    }

    public void setPainel_alterar_senha(JPanel Painel_alterar_senha) {
        this.Painel_alterar_senha = Painel_alterar_senha;
    }

    public JButton getBtnAlterar_senha() {
        return btnAlterar_senha;
    }

    public void setBtnAlterar_senha(JButton btnAlterar_senha) {
        this.btnAlterar_senha = btnAlterar_senha;
    }

    public JLabel getLblCpf() {
        return lblCpf;
    }

    public void setLblCpf(JLabel lblCpf) {
        this.lblCpf = lblCpf;
    }

    public JLabel getLblIntroduçãoAlterar() {
        return lblIntroduçãoAlterar;
    }

    public void setLblIntroduçãoAlterar(JLabel lblIntroduçãoAlterar) {
        this.lblIntroduçãoAlterar = lblIntroduçãoAlterar;
    }

    public JLabel getLblSenhaNova() {
        return lblSenhaNova;
    }

    public void setLblSenhaNova(JLabel lblSenhaNova) {
        this.lblSenhaNova = lblSenhaNova;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIntroduçãoAlterar = new javax.swing.JLabel();
        Painel_alterar_senha = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        InsertAlterar_cpf = new javax.swing.JTextField();
        lblSenhaNova = new javax.swing.JLabel();
        InsertAlterar_senhaNova = new javax.swing.JTextField();
        btnAlterar_senha = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIntroduçãoAlterar.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        lblIntroduçãoAlterar.setText("Insira as informações para alterar senha");

        Painel_alterar_senha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCpf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCpf.setText("CPF:");

        lblSenhaNova.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSenhaNova.setText("Nova Senha:");

        btnAlterar_senha.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnAlterar_senha.setText("Alterar senha");
        btnAlterar_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar_senhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_alterar_senhaLayout = new javax.swing.GroupLayout(Painel_alterar_senha);
        Painel_alterar_senha.setLayout(Painel_alterar_senhaLayout);
        Painel_alterar_senhaLayout.setHorizontalGroup(
            Painel_alterar_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_alterar_senhaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Painel_alterar_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSenhaNova)
                    .addComponent(lblCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_alterar_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsertAlterar_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertAlterar_senhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_alterar_senhaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterar_senha)
                .addGap(122, 122, 122))
        );
        Painel_alterar_senhaLayout.setVerticalGroup(
            Painel_alterar_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_alterar_senhaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Painel_alterar_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(InsertAlterar_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Painel_alterar_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaNova)
                    .addComponent(InsertAlterar_senhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnAlterar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/aa.png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIntroduçãoAlterar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Painel_alterar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblIntroduçãoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel_alterar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterar_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar_senhaActionPerformed
        control.atualizarSenha();
    }//GEN-LAST:event_btnAlterar_senhaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        investidor_window investidorWindow = new investidor_window(investidor);
        investidorWindow.setVisible(true); 
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Alterar_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Alterar_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Alterar_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Alterar_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Alterar_window().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InsertAlterar_cpf;
    private javax.swing.JTextField InsertAlterar_senhaNova;
    private javax.swing.JPanel Painel_alterar_senha;
    private javax.swing.JButton btnAlterar_senha;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblIntroduçãoAlterar;
    private javax.swing.JLabel lblSenhaNova;
    // End of variables declaration//GEN-END:variables
}
