/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller_ConsultarSaldo;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Investidor;

/**
 *
 * @author rgara
 */
public class ConsultarSaldo_window extends javax.swing.JFrame {

    
    private Controller_ConsultarSaldo controlConsultarSaldo;
    private Investidor investidor;
    /**
     * Creates new form ConsutarSaldo_window
     */
    public ConsultarSaldo_window(Investidor investidor) {
        initComponents();
        this.investidor = investidor;
        this.controlConsultarSaldo = new Controller_ConsultarSaldo(this, investidor);
    }

    public JTextArea getAreaConsulta() {
        return AreaConsulta;
    }

    public void setAreaConsulta(JTextArea AreaConsulta) {
        this.AreaConsulta = AreaConsulta;
    }

    public JTextField getInsertSenhaConsulta() {
        return InsertSenhaConsulta;
    }

    public void setInsertSenhaConsulta(JTextField InsertSenhaConsulta) {
        this.InsertSenhaConsulta = InsertSenhaConsulta;
    }   

    public JButton getBtnVerSaldo() {
        return btnVerSaldo;
    }

    public void setBtnVerSaldo(JButton btnVerSaldo) {
        this.btnVerSaldo = btnVerSaldo;
    }

    public JButton getBtnVoltarMenu() {
        return btnVoltarMenu;
    }

    public void setBtnVoltarMenu(JButton btnVoltarMenu) {
        this.btnVoltarMenu = btnVoltarMenu;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblIntroducaoSenha() {
        return lblIntroducaoSenha;
    }

    public void setLblIntroducaoSenha(JLabel lblIntroducaoSenha) {
        this.lblIntroducaoSenha = lblIntroducaoSenha;
    }

    public JLabel getLblSenhaConsultar() {
        return lblSenhaConsultar;
    }

    public void setLblSenhaConsultar(JLabel lblSenhaConsultar) {
        this.lblSenhaConsultar = lblSenhaConsultar;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltarMenu = new javax.swing.JButton();
        lblIntroducaoSenha = new javax.swing.JLabel();
        btnVerSaldo = new javax.swing.JButton();
        lblSenhaConsultar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaConsulta = new javax.swing.JTextArea();
        InsertSenhaConsulta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("consultar saldo window");

        btnVoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/aa.png"))); // NOI18N
        btnVoltarMenu.setBorderPainted(false);
        btnVoltarMenu.setContentAreaFilled(false);
        btnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuActionPerformed(evt);
            }
        });

        lblIntroducaoSenha.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblIntroducaoSenha.setText("Insira sua senha para ver seu Saldo");

        btnVerSaldo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnVerSaldo.setText("Ver saldo");
        btnVerSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSaldoActionPerformed(evt);
            }
        });

        lblSenhaConsultar.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblSenhaConsultar.setText("Senha:");

        AreaConsulta.setColumns(20);
        AreaConsulta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AreaConsulta.setRows(5);
        jScrollPane1.setViewportView(AreaConsulta);

        InsertSenhaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertSenhaConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltarMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblSenhaConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsertSenhaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblIntroducaoSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnVerSaldo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIntroducaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaConsultar)
                    .addComponent(InsertSenhaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerSaldo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSaldoActionPerformed
        // TODO add your handling code here:
        String senha = InsertSenhaConsulta.getText();
        if (senha.length() == 6 && senha.matches("\\d+")) {
            controlConsultarSaldo.consultarSaldo(senha);
        } else {
            JOptionPane.showMessageDialog(this, "A senha deve conter exatamente 6 dígitos numéricos.", "Erro de validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerSaldoActionPerformed

    private void btnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        investidor_window investidorWindow = new investidor_window(investidor);
        investidorWindow.setVisible(true); 
        investidorWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVoltarMenuActionPerformed

    private void InsertSenhaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertSenhaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertSenhaConsultaActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaConsulta;
    private javax.swing.JTextField InsertSenhaConsulta;
    private javax.swing.JButton btnVerSaldo;
    private javax.swing.JButton btnVoltarMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIntroducaoSenha;
    private javax.swing.JLabel lblSenhaConsultar;
    // End of variables declaration//GEN-END:variables
}
