/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.sun.jdi.connect.spi.Connection;
import controller.Controller_MovimentoReais;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Investidor;

/**
 *
 * @author rgara
 */
public class DepositarReais_window extends javax.swing.JFrame {

    private Investidor investidor;
    private Controller_MovimentoReais controller;
    
    public DepositarReais_window(Investidor investidor) {
    initComponents();
    this.investidor = investidor;
    this.controller = new Controller_MovimentoReais(investidor, this);
}

    public JTextArea getAreaSaldoPosDeposito() {
        return AreaSaldoPosDeposito;
    }

    public void setAreaSaldoPosDeposito(String texto) {
        AreaSaldoPosDeposito.setText(texto);
    }

    public JTextField getInsertValorDeposito() {
        return InsertValorDeposito;
    }

    public void setInsertValorDeposito(JTextField InsertValorDeposito) {
        this.InsertValorDeposito = InsertValorDeposito;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    public JButton getBtndepositar() {
        return btndepositar;
    }

    public void setBtndepositar(JButton btndepositar) {
        this.btndepositar = btndepositar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblIntroducaoDepositar() {
        return lblIntroducaoDepositar;
    }

    public void setLblIntroducaoDepositar(JLabel lblIntroducaoDepositar) {
        this.lblIntroducaoDepositar = lblIntroducaoDepositar;
    }

    public JLabel getLblValor() {
        return lblValor;
    }

    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblIntroducaoDepositar = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        InsertValorDeposito = new javax.swing.JTextField();
        btndepositar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaSaldoPosDeposito = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("depositar reais window");

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/aa.png"))); // NOI18N
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setDefaultCapable(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblIntroducaoDepositar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblIntroducaoDepositar.setText("Insira o valor que deseja depositar");

        lblValor.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblValor.setText("R$:");

        InsertValorDeposito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btndepositar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btndepositar.setText("Depositar");
        btndepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositarActionPerformed(evt);
            }
        });

        AreaSaldoPosDeposito.setColumns(20);
        AreaSaldoPosDeposito.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AreaSaldoPosDeposito.setRows(5);
        jScrollPane1.setViewportView(AreaSaldoPosDeposito);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVoltar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblIntroducaoDepositar)))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(lblValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndepositar)
                    .addComponent(InsertValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIntroducaoDepositar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(InsertValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btndepositar)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositarActionPerformed
        // TODO add your handling code here:
        String valorTexto = InsertValorDeposito.getText().trim();
        if (valorTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor para depósito.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            controller.realizarDeposito(valorTexto);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao realizar o depósito: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btndepositarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        investidor_window investidorWindow = new investidor_window(investidor);
        investidorWindow.setVisible(true); 
        investidorWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaSaldoPosDeposito;
    private javax.swing.JTextField InsertValorDeposito;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btndepositar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIntroducaoDepositar;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
