/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller_MovimentoReais;
import controller.Controller_SacarReais;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Investidor;

/**
 *
 * @author rgara
 */
public class SacarReais_window extends javax.swing.JFrame {

    private Investidor investidor;
    private Controller_SacarReais controller;
    
    public SacarReais_window(Investidor investidor) {
        initComponents();
        this.investidor = investidor;
        this.controller = new Controller_SacarReais(investidor, this);
    }

    public Investidor getInvestidor() {
        return investidor;
    }

    public void setInvestidor(Investidor investidor) {
        this.investidor = investidor;
    }

    public Controller_SacarReais getController() {
        return controller;
    }

    public void setController(Controller_SacarReais controller) {
        this.controller = controller;
    }

    public JTextArea getAreaSaldoPosSaque() {
        return AreaSaldoPosSaque;
    }

    
    public void setAreaSaldoPosSaque(String texto) {
        AreaSaldoPosSaque.setText(texto);
    }

    public JTextField getInsertValorSacar() {
        return InsertValorSacar;
    }

    public void setInsertValorSacar(JTextField InsertValorSacar) {
        this.InsertValorSacar = InsertValorSacar;
    }

    public JButton getBtnSacar() {
        return btnSacar;
    }

    public void setBtnSacar(JButton btnSacar) {
        this.btnSacar = btnSacar;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblIntroducaoSacar() {
        return lblIntroducaoSacar;
    }

    public void setLblIntroducaoSacar(JLabel lblIntroducaoSacar) {
        this.lblIntroducaoSacar = lblIntroducaoSacar;
    }

    public JLabel getLblValor() {
        return lblValor;
    }

    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblIntroducaoSacar = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        InsertValorSacar = new javax.swing.JTextField();
        btnSacar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaSaldoPosSaque = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("sacar");

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/aa.png"))); // NOI18N
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setDefaultCapable(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblIntroducaoSacar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblIntroducaoSacar.setText("Insira o valor que deseja sacar");

        lblValor.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblValor.setText("R$:");

        InsertValorSacar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnSacar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        AreaSaldoPosSaque.setColumns(20);
        AreaSaldoPosSaque.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AreaSaldoPosSaque.setRows(5);
        jScrollPane1.setViewportView(AreaSaldoPosSaque);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addGap(18, 18, 18)
                                .addComponent(lblIntroducaoSacar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSacar)
                            .addComponent(InsertValorSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnVoltar)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIntroducaoSacar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(InsertValorSacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSacar)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        investidor_window investidorWindow = new investidor_window(investidor);
        investidorWindow.setVisible(true); 
        investidorWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        // TODO add your handling code here:
        String valorTexto = InsertValorSacar.getText().trim();
        if (valorTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor para depósito.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            controller.realizarSaque(valorTexto);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao realizar o depósito: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaSaldoPosSaque;
    private javax.swing.JTextField InsertValorSacar;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIntroducaoSacar;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
