/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller_VendaCrypto;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Investidor;

/**
 *
 * @author rgara
 */
public class VenderCrypto_window extends javax.swing.JFrame {

    private Investidor investidor;
    private Controller_VendaCrypto controller;

    public VenderCrypto_window(Investidor investidor) {
        initComponents();
        this.investidor = investidor;
        controller = new Controller_VendaCrypto(investidor, this);
    }

    public JTextArea getAreaConsultarCotacaoVenda() {
        return AreaConsultarCotacaoVenda;
    }

    public void setAreaConsultarCotacaoVenda(JTextArea AreaConsultarCotacaoVenda) {
        this.AreaConsultarCotacaoVenda = AreaConsultarCotacaoVenda;
    }

    public JTextField getInsertReaisVender() {
        return InsertReaisVender;
    }

    public void setInsertReaisVender(JTextField InsertReaisVender) {
        this.InsertReaisVender = InsertReaisVender;
    }

    public JTextField getInsertSenhaVendaCrypto() {
        return InsertSenhaVendaCrypto;
    }

    public void setInsertSenhaVendaCrypto(JTextField InsertSenhaVendaCrypto) {
        this.InsertSenhaVendaCrypto = InsertSenhaVendaCrypto;
    }

    public JRadioButton getRadioBitcoin() {
        return RadioBitcoin;
    }

    public void setRadioBitcoin(JRadioButton RadioBitcoin) {
        this.RadioBitcoin = RadioBitcoin;
    }

    public JRadioButton getRadioEthereum() {
        return RadioEthereum;
    }

    public void setRadioEthereum(JRadioButton RadioEthereum) {
        this.RadioEthereum = RadioEthereum;
    }

    public JRadioButton getRadioRipple() {
        return RadioRipple;
    }

    public void setRadioRipple(JRadioButton RadioRipple) {
        this.RadioRipple = RadioRipple;
    }

    public JButton getBtnVender() {
        return btnVender;
    }

    public void setBtnVender(JButton btnVender) {
        this.btnVender = btnVender;
    }

    public JButton getBtnVerCotacao() {
        return btnVerCotacao;
    }

    public void setBtnVerCotacao(JButton btnVerCotacao) {
        this.btnVerCotacao = btnVerCotacao;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblIntroducaoVenda() {
        return lblIntroducaoVenda;
    }

    public void setLblIntroducaoVenda(JLabel lblIntroducaoVenda) {
        this.lblIntroducaoVenda = lblIntroducaoVenda;
    }

    public JLabel getLblSenha() {
        return lblSenha;
    }

    public void setLblSenha(JLabel lblSenha) {
        this.lblSenha = lblSenha;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblIntroducaoVenda = new javax.swing.JLabel();
        InsertReaisVender = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaConsultarCotacaoVenda = new javax.swing.JTextArea();
        btnVender = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        InsertSenhaVendaCrypto = new javax.swing.JTextField();
        btnVerCotacao = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        RadioBitcoin = new javax.swing.JRadioButton();
        RadioEthereum = new javax.swing.JRadioButton();
        RadioRipple = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/aa.png"))); // NOI18N
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setDefaultCapable(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Valor em reais para retirar");

        lblIntroducaoVenda.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblIntroducaoVenda.setText("Insira a senha para vender a crypto e ver cotação");

        AreaConsultarCotacaoVenda.setColumns(20);
        AreaConsultarCotacaoVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AreaConsultarCotacaoVenda.setRows(5);
        jScrollPane1.setViewportView(AreaConsultarCotacaoVenda);

        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        lblSenha.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblSenha.setText("Senha:");

        btnVerCotacao.setText("Ver Cotação");
        btnVerCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCotacaoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        RadioBitcoin.setText("Bitcoin");

        RadioEthereum.setText("Ethereum");

        RadioRipple.setText("Ripple");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RadioEthereum)
                    .addComponent(RadioRipple, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioBitcoin, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RadioBitcoin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioEthereum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioRipple)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVoltar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblIntroducaoVenda))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(lblSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InsertSenhaVendaCrypto, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnVerCotacao)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnVender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertReaisVender, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIntroducaoVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(InsertSenhaVendaCrypto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerCotacao)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(InsertReaisVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnVender)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        investidor_window investidorWindow = new investidor_window(investidor);
        investidorWindow.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        String moedaEscolhida = "";
        if (RadioBitcoin.isSelected()) {
            moedaEscolhida = "bitcoin";
        } else if (RadioEthereum.isSelected()) {
            moedaEscolhida = "ethereum";
        } else if (RadioRipple.isSelected()) {
            moedaEscolhida = "ripple";
        }

        try {
            double valorEmReais = Double.parseDouble(InsertReaisVender.getText());
            controller.venderCrypto(moedaEscolhida, valorEmReais);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor numérico válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao realizar a venda: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnVerCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCotacaoActionPerformed
        // TODO add your handling code here:
        controller.Cotacoes();
    }//GEN-LAST:event_btnVerCotacaoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VenderCrypto_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VenderCrypto_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VenderCrypto_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VenderCrypto_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VenderCrypto_window().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaConsultarCotacaoVenda;
    private javax.swing.JTextField InsertReaisVender;
    private javax.swing.JTextField InsertSenhaVendaCrypto;
    private javax.swing.JRadioButton RadioBitcoin;
    private javax.swing.JRadioButton RadioEthereum;
    private javax.swing.JRadioButton RadioRipple;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVerCotacao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIntroducaoVenda;
    private javax.swing.JLabel lblSenha;
    // End of variables declaration//GEN-END:variables
}
